export default {
  HOME: 'Home',
  EVIDENCE_FOR_JESUS: 'EvidenceForJesus',
  PROJECT_DETAILS: 'ProjectDetails',
  PORTFOLIO: 'Portfolio',
  SETTINGS: 'Settings',
  CPHILIPSE: 'CPHILIPSE',
  UNAUTHORIZED: 'Unauthorized',
  UNAUTHENTICATED: 'Unauthenticated',
  AUTHENTICATED: 'Authenticated',
  FALLBACK: 'Fallback',
  SHARED_ELEMENT: 'SharedElementTransition',
  SHARED_ELEMENT_DETAILS: 'SharedElementTransitionDetails',
  SHARED_ELEMENT_PAGE: 'SharedElementTransitionPage',
};
