export default {
  HOME: 'Home',
  LOGIN: 'Login',
  REGISTER: 'Register',
  ARTICLE_DETAILS: 'Article',
  COMMENTS: 'Comments',
  PROFILE: 'Profile',
  PORTFOLIO: 'Portfolio',
  SETTINGS: 'Settings',
  CONTACT: 'Contact',
  UNAUTHORIZED: 'Unauthorized',
  UNAUTHENTICATED: 'Unauthenticated',
  AUTHENTICATED: 'Authenticated',
  FALLBACK: 'Fallback',
};
