export default {
  cphilipse: require('../assets/images/cphilipse.jpg'),
  hvgea: require('../assets/images/hvgea.png'),
  hvgea_app01: require('../assets/images/hvgea_app01.jpg'),
  hvgea_app02: require('../assets/images/hvgea_app02.jpg'),
  hvgea_app03: require('../assets/images/hvgea_app03.jpg'),
  hvgea_app04: require('../assets/images/hvgea_app04.jpg'),
  hvgea_app05: require('../assets/images/hvgea_app05.jpg'),
  hvgea_app06: require('../assets/images/hvgea_app06.jpg'),
  hvgea_app07: require('../assets/images/hvgea_app07.jpg'),
  hvgea_app08: require('../assets/images/hvgea_app08.jpg'),
  hvgea_app09: require('../assets/images/hvgea_app09.jpg'),
  hvgea_app10: require('../assets/images/hvgea_app10.jpg'),
  hvgea_app11: require('../assets/images/hvgea_app11.jpg'),
  hvgea_app12: require('../assets/images/hvgea_app12.jpg'),
  hvgea_app13: require('../assets/images/hvgea_app13.jpg'),
  hvgea_icon: require('../assets/images/hvgea_icon.png'),
  app_home: require('../assets/images/App_Home.jpg'),
  app_menu: require('../assets/images/App_Menu.jpg'),
  app_icon: require('../assets/images/icon.png'),
  android_default_icon: require('../assets/images/android_default_icon.png'),
};
